config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
devise_for :users
as :user do
	get 'signin' => 'devise/sessions#new'
	delete 'signout' => 'devise/sessions#destroy'
	get 'signup' => 'devise/registrations#new'
end	 
root "pages#home"

get 'about' => 'pages#about' 
get 'contactus' => 'pages#contactus' 
get 'myteam' => 'pages#myteam' 
get 'courses' => 'pages#courses' 
get 'learnmore' => 'pages#learnmore' 
get 'membership' => 'pages#membership' 
get 'seminars' => 'pages#seminars' 


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_authorization.rb
class AdminAuthorization < ActiveAdmin::AuthorizationAdapter
	
	def authorized? (action, subject = nil)
		user && user.admin?
	end	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def access_denied(exception)
  	redirect_to root_path, alert: exception.message
  end	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mind Meditate</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Navigation Bar -->
    <nav class="navbar navbar-toggleable-sm navbar-inverse bg-inverse">
      <div class="container">
        <%= link_to "Mind Meditate", root_path, class: "navbar-brand" %>
        <ul class="nav navbar-nav">
          <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "My Team", myteam_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Contact Us", contactus_path, class: "nav-link" %></li>
      </div>
      </div>    
          <% if user_signed_in? %>
           
            <li class="nav-item pull-md-right"><%= link_to "Log Out", signout_path, method: :delete, class: "nav-link" %></li>
          <% else %>

            <li class="nav-item pull-md-right "><%= link_to "Sign In ", signin_path, class: "nav-link" %></li> 
            <li class="nav-item pull-md-right "><%= link_to "Sign Up ", signup_path, class: "nav-link btn btn-primary " %></li>

          <% end %> 

        </ul>
      </div>
    </nav>
    
    <% flash.each do |name, message| %>
      <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
    <% end %>
    <!-- Page Content -->
    <%= yield %>
    
    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>© 2017 Mind Meditate</p>
        </center>
      </div>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>About us</h1>
        <p>Education is the most powerful weapon which you can use to change the world ~ Nelson Mandela. Mindmeditate is a learning experience organization that publishes ideas and teachings by the best teachers in personal growth, health and fitness, spirituality, productivity, mindfulness and more – serving millions of students, members and followers worldwide. </p>
        <p>Through our digital education platforms, online academies, mobile apps, content platforms and live events, we give you access to transformational knowledge that empowers you to expand your boundaries, unleash your potential and lead an extraordinary life – on your terms.  </p>
		<p>We are ambitiously determined to push humanity forward by empowering our audience to live healthier and happier lives, to unleash their fullest potential – to be extraordinary. How? Nelson Mandela affirmed it: with the most powerful tool of all – education. We wanted want to change education globally and provide innovative, holistic education for all levels – from infant learning and highschool models to all stages of adulthood.</p>

    </div>

app/views/pages/contactus.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>Contact Us</h1>
        <p>This is the sample project I built for <a href="https://onemonthrails.com">One Month Rails</a>.</p>
    </div>
</div>

app/views/pages/courses.erb
<div class="jumbotron">
    <div class="container">
        <h1>Courses</h1>
        <p> Online Courses for your learning</p>
    </div>
</div>

app/views/pages/home.html.erb
 <% if user_signed_in? %>
 <div class="jumbotron jumbotron-home">
        <div class="container">
    <h1> Welcome Back. Let's Start Learning</h1>
        </div>
 </div>              
<% else %>   
    <div class="jumbotron jumbotron-home">
        <div class="container">
           
            
            
            <h1>Welcome to Mind Meditate Academy!</h1>
            <p>We design learning experiences and share the teaching in transformational education for student around the world </p>
            <%= link_to "Learn more »", learnmore_path, class: "btn btn-primary btn-lg" %> 
          
        </div>
    </div>
    <div class="container">
        <div class="col">
            <div class="col-md-10">
                <h2>Online Courses</h2>
                <p>We are offering courses that can help to elevate yourself in every aspect of life. We affiliate with the expert in each of the subjects. You will enjoy monthly free courses or win attractive prizes  </p>
                <p><%= link_to "View details", courses_path, class: "btn btn-secondary" %></p>
            </div>
            <div class="col-md-10">
                <h2>Seminars</h2>
                <p>Come join us live in every happening places around the world and start to learn to hack your believe systems. Live your dream </p>
                <p><%= link_to "View details", seminars_path, class: "btn btn-secondary" %></p>
            </div>
            <div class="col-md-10">
                <h2>Membership</h2>
                <p>Signing Up to our membership will provide many benefits such as discounts to attend our seminars, purchase our product and also enable you to collect points to earn attractive prizes from our affiliates </p>
                <p><%= link_to "View details", membership_path, class: "btn btn-secondary" %></p>
            </div>
        </div>
    </div>
<% end %>   

app/views/pages/learnmore.erb
<div class="jumbotron">
    <div class="container">
        <h1>Learn More</h1>
        <p>Be Extraordinary</a>.</p>
    </div>
</div>

app/views/pages/membership.erb
<div class="jumbotron">
    <div class="container">
        <h1>Sign Up for Membership</h1>
        <p>Please select for the membership Option as below </p>
        <ul> 
        	<li> free membership </li>
        	<li> full membership </li>

    </div>
</div>

app/views/pages/myteam.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>Our Team</h1>
        <p>Mindmeditate runs a unique team of 20 extraordinary players and bright minds from almost every different part of nations, all of whom celebrate and contribute to our company culture, and collectively work towards a mutual goal and purpose. We stand for ideas, companies and products that push humanity forward and unleash the extraordinary in everyone, with the adamant belief that we can and will impact the world.</p>
    </div>
</div>

app/views/pages/seminars.erb
<div class="jumbotron">
    <div class="container">
        <h1>Seminar</h1>
        <p>Please see our next Events around the globe</a>.</p>
    </div>
</div>